2023-03-27 00:23:51,281 [1] INFO  FantasyOfSango.SangoServer - Sango Server is Running
2023-03-27 00:23:51,294 [1] INFO  FantasyOfSango.SangoServer - Init all Component
2023-03-27 00:23:51,294 [1] INFO  Photon.SocketServer.ApplicationBase - Application start: AppId=SangoTest; AppPath=D:\FantasyOfSango\Server\TestServer\Photon_v4\FantasyOfSango_Photon\deploy\FantasyOfSango, Type=FantasyOfSango.SangoServer 
2023-03-27 00:25:31,084 [15] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 00:26:24,833 [14] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 00:32:45,494 [1] INFO  Photon.SocketServer.ApplicationBase - Application is stopping: AppId=SangoTest
2023-03-27 00:32:45,500 [16] ERROR Photon.SocketServer.ApplicationBase - System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at FantasyOfSango.Threads.SyncPlayerTransformThreads.Update() in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Threads\SyncPlayerTransformThreads.cs:line 27
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2023-03-27 00:32:45,515 [1] INFO  FantasyOfSango.SangoServer - Sango Server is Shut Down
2023-03-27 00:32:45,515 [1] INFO  Photon.SocketServer.ApplicationBase - Application stop: AppId=SangoTest
2023-03-27 15:15:15,784 [1] INFO  FantasyOfSango.SangoServer - Sango Server is Running
2023-03-27 15:15:15,797 [1] INFO  FantasyOfSango.SangoServer - Init all Component
2023-03-27 15:15:15,798 [1] INFO  Photon.SocketServer.ApplicationBase - Application start: AppId=SangoTest; AppPath=D:\FantasyOfSango\Server\TestServer\Photon_v4\FantasyOfSango_Photon\deploy\FantasyOfSango, Type=FantasyOfSango.SangoServer 
2023-03-27 15:15:48,871 [12] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 15:26:52,679 [10] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 19:50:00,947 [11] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 19:53:02,484 [10] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 19:56:46,680 [12] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 19:59:01,129 [9] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:2,ip:127.0.0.1:60417, Data: F3-02-07-00-01-08-73-01-25-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-38-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-37-2E-36-31-38-39-34-32-2C-22-59-22-3A-32-35-2E-35-33-39-30-37-33-39-2C-22-5A-22-3A-31-36-33-2E-30-38-34-34-35-37-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-30-30-38-30-38-37-2C-22-59-22-3A-32-35-2E-32-37-35-39-39-31-34-2C-22-5A-22-3A-31-36-32-2E-33-32-37-30-35-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-31-3A-35-39-3A-30-30-2E-39-38-39-39-36-38-32-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 19:59:22,761 [22] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:2,ip:127.0.0.1:60417, Data: F3-02-07-00-01-08-73-01-26-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-37-2E-36-32-31-38-38-37-2C-22-59-22-3A-32-35-2E-35-31-36-37-34-32-37-2C-22-5A-22-3A-31-36-32-2E-37-32-32-30-39-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-30-30-38-30-38-37-2C-22-59-22-3A-32-35-2E-32-37-35-39-39-31-34-2C-22-5A-22-3A-31-36-32-2E-33-32-37-30-35-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-31-3A-35-39-3A-32-32-2E-36-33-34-30-35-39-39-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 19:59:39,494 [12] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:2,ip:127.0.0.1:60417, Data: F3-02-07-00-01-08-73-01-26-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-37-2E-36-32-31-38-38-37-2C-22-59-22-3A-32-35-2E-35-31-36-37-34-32-37-2C-22-5A-22-3A-31-36-32-2E-37-32-32-30-39-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-30-30-38-30-38-37-2C-22-59-22-3A-32-35-2E-32-37-35-39-39-31-34-2C-22-5A-22-3A-31-36-32-2E-33-32-37-30-35-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-31-3A-35-39-3A-33-39-2E-33-35-35-38-35-34-35-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:03:56,074 [22] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:2,ip:127.0.0.1:60417, Data: F3-02-07-00-01-08-73-01-24-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-37-2E-36-32-31-38-38-37-2C-22-59-22-3A-32-35-2E-35-31-36-37-34-32-37-2C-22-5A-22-3A-31-36-32-2E-37-32-32-30-39-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-30-30-38-30-38-37-2C-22-59-22-3A-32-35-2E-32-37-35-39-39-31-34-2C-22-5A-22-3A-31-36-32-2E-33-32-37-30-35-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-30-33-3A-35-35-2E-39-34-38-32-38-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:03:58,729 [13] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:2,ip:127.0.0.1:60417, Data: F3-02-07-00-01-08-73-01-26-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-37-2E-36-32-31-38-38-37-2C-22-59-22-3A-32-35-2E-35-31-36-37-34-32-37-2C-22-5A-22-3A-31-36-32-2E-37-32-32-30-39-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-30-30-38-30-38-37-2C-22-59-22-3A-32-35-2E-32-37-35-39-39-31-34-2C-22-5A-22-3A-31-36-32-2E-33-32-37-30-35-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-30-33-3A-35-38-2E-36-30-32-33-38-36-33-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:04:01,257 [20] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:2,ip:127.0.0.1:60417, Data: F3-02-07-00-01-08-73-01-25-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-37-2E-36-32-31-38-38-37-2C-22-59-22-3A-32-35-2E-35-31-36-37-34-32-37-2C-22-5A-22-3A-31-36-32-2E-37-32-32-30-39-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-30-30-38-30-38-37-2C-22-59-22-3A-32-35-2E-32-37-35-39-39-31-34-2C-22-5A-22-3A-31-36-32-2E-33-32-37-30-35-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-30-34-3A-30-31-2E-31-32-37-38-36-34-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:04:03,647 [19] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:2,ip:127.0.0.1:60417, Data: F3-02-07-00-01-08-73-01-25-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-37-2E-36-32-31-38-38-37-2C-22-59-22-3A-32-35-2E-35-31-36-37-34-32-37-2C-22-5A-22-3A-31-36-32-2E-37-32-32-30-39-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-30-30-38-30-38-37-2C-22-59-22-3A-32-35-2E-32-37-35-39-39-31-34-2C-22-5A-22-3A-31-36-32-2E-33-32-37-30-35-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-30-34-3A-30-33-2E-35-31-31-31-37-37-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:04:08,953 [21] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:2,ip:127.0.0.1:60417, Data: F3-02-07-00-01-08-73-01-26-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-37-2E-36-32-31-38-38-37-2C-22-59-22-3A-32-35-2E-35-31-36-37-34-32-37-2C-22-5A-22-3A-31-36-32-2E-37-32-32-30-39-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-30-30-38-30-38-37-2C-22-59-22-3A-32-35-2E-32-37-35-39-39-31-34-2C-22-5A-22-3A-31-36-32-2E-33-32-37-30-35-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-30-34-3A-30-38-2E-38-32-33-35-35-35-33-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:04:27,013 [4] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:2,ip:127.0.0.1:60417, Data: F3-02-07-00-01-08-73-01-26-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-37-2E-36-32-31-38-38-37-2C-22-59-22-3A-32-35-2E-35-31-36-37-34-32-37-2C-22-5A-22-3A-31-36-32-2E-37-32-32-30-39-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-30-30-38-30-38-37-2C-22-59-22-3A-32-35-2E-32-37-35-39-39-31-34-2C-22-5A-22-3A-31-36-32-2E-33-32-37-30-35-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-30-34-3A-32-36-2E-38-39-31-32-36-31-34-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:08:20,676 [20] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:2,ip:127.0.0.1:60417, Data: F3-02-07-00-01-08-73-01-24-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-32-33-39-35-36-33-2C-22-59-22-3A-32-35-2E-34-34-32-30-33-2C-22-5A-22-3A-31-36-31-2E-35-32-36-37-34-39-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-35-39-2E-30-30-38-30-38-37-2C-22-59-22-3A-32-35-2E-32-37-35-39-39-31-34-2C-22-5A-22-3A-31-36-32-2E-33-32-37-30-35-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-30-38-3A-32-30-2E-35-35-30-31-34-39-35-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:12:18,156 [13] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 20:12:29,709 [18] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 20:13:07,849 [16] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:3,ip:127.0.0.1:60464, Data: F3-02-07-00-01-08-73-01-29-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-33-2E-30-33-34-32-39-30-33-2C-22-59-22-3A-2D-30-2E-37-32-31-33-33-39-37-30-33-2C-22-5A-22-3A-35-32-2E-31-36-34-34-35-31-36-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-31-33-2E-39-35-32-30-32-30-36-2C-22-59-22-3A-2D-30-2E-39-31-34-36-32-33-30-32-32-2C-22-5A-22-3A-35-34-2E-37-37-30-39-31-39-38-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-31-33-3A-30-37-2E-36-38-30-36-30-37-35-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:17:43,545 [18] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 20:18:32,736 [20] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 20:19:59,569 [19] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:4,ip:127.0.0.1:57099, Data: F3-02-07-00-01-08-73-01-1C-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-38-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-30-2E-34-30-38-35-37-37-2C-22-59-22-3A-35-2E-36-33-30-36-30-37-36-2C-22-5A-22-3A-31-32-33-2E-30-33-33-38-32-39-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-35-35-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-31-39-3A-35-39-2E-35-34-35-30-34-37-34-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:20:12,887 [22] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 20:23:28,845 [12] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 20:25:34,534 [13] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 20:26:57,173 [19] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 20:29:37,704 [4] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 20:31:59,348 [20] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 20:32:30,305 [21] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:7,ip:127.0.0.1:52631, Data: F3-02-07-00-01-08-73-01-1E-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-38-2E-37-34-38-37-35-36-34-2C-22-59-22-3A-35-2E-35-34-34-37-38-33-31-32-2C-22-5A-22-3A-31-32-32-2E-31-34-38-37-35-38-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-33-32-3A-33-30-2E-32-37-35-39-36-35-37-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:36:12,728 [18] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 20:36:41,041 [19] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 20:36:52,533 [22] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:8,ip:127.0.0.1:56592, Data: F3-02-07-00-01-08-73-01-1D-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-38-2E-34-32-36-30-31-30-31-2C-22-59-22-3A-35-2E-33-38-30-37-35-33-35-32-2C-22-5A-22-3A-31-32-31-2E-34-33-36-33-34-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-35-35-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-33-36-3A-35-32-2E-34-35-33-31-33-39-38-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:37:03,139 [17] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:8,ip:127.0.0.1:56592, Data: F3-02-07-00-01-08-73-01-1D-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-38-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-30-2E-34-35-35-33-37-35-37-2C-22-59-22-3A-35-2E-37-30-38-36-32-37-37-2C-22-5A-22-3A-31-32-33-2E-32-39-37-36-35-33-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-35-35-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-33-37-3A-30-33-2E-31-30-36-30-32-36-38-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:37:54,808 [12] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 20:38:59,784 [22] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 20:39:26,594 [13] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:9,ip:127.0.0.1:61979, Data: F3-02-07-00-01-08-73-01-1E-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-30-2E-34-35-35-33-31-34-36-2C-22-59-22-3A-35-2E-38-36-30-35-36-38-30-35-2C-22-5A-22-3A-31-32-33-2E-38-30-39-33-37-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-36-39-39-36-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-33-39-3A-32-36-2E-35-36-31-30-30-39-32-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:39:32,317 [21] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:9,ip:127.0.0.1:61979, Data: F3-02-07-00-01-08-73-01-1C-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-31-2E-31-30-32-35-34-36-37-2C-22-59-22-3A-35-2E-39-35-34-38-35-30-32-2C-22-5A-22-3A-31-32-34-2E-34-33-34-35-34-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-35-35-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-33-39-3A-33-32-2E-32-39-37-39-32-34-32-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:39:37,369 [18] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:9,ip:127.0.0.1:61979, Data: F3-02-07-00-01-08-73-01-1C-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-38-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-31-2E-31-30-32-35-34-36-37-2C-22-59-22-3A-35-2E-39-35-34-38-34-39-32-34-2C-22-5A-22-3A-31-32-34-2E-34-33-34-35-34-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-32-3A-33-39-3A-33-37-2E-33-34-35-39-38-38-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 20:40:56,341 [9] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 21:15:06,079 [21] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 21:15:23,098 [22] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:10,ip:127.0.0.1:58127, Data: F3-02-07-00-01-08-73-01-1D-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-38-2E-36-37-34-32-30-39-36-2C-22-59-22-3A-35-2E-35-33-39-38-32-32-31-2C-22-5A-22-3A-31-32-32-2E-31-30-38-31-35-34-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-33-3A-31-35-3A-32-32-2E-30-34-34-37-37-31-35-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 21:16:25,045 [10] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:10,ip:127.0.0.1:58127, Data: F3-02-07-00-01-08-73-01-1D-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-38-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-31-2E-38-37-39-30-37-34-31-2C-22-59-22-3A-35-2E-37-34-34-35-37-31-36-39-2C-22-5A-22-3A-31-32-34-2E-30-30-33-38-39-31-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-35-35-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-33-3A-31-36-3A-32-35-2E-30-31-34-33-36-38-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 21:16:28,002 [18] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:10,ip:127.0.0.1:58127, Data: F3-02-07-00-01-08-73-01-1E-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-31-2E-38-37-39-30-37-34-31-2C-22-59-22-3A-35-2E-37-34-34-35-37-31-36-39-2C-22-5A-22-3A-31-32-34-2E-30-30-33-38-39-31-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-33-3A-31-36-3A-32-37-2E-39-36-39-39-33-33-39-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 21:16:41,212 [12] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:10,ip:127.0.0.1:58127, Data: F3-02-07-00-01-08-73-01-1B-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-38-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-31-2E-38-37-39-30-37-34-31-2C-22-59-22-3A-35-2E-37-34-34-35-37-31-36-39-2C-22-5A-22-3A-31-32-34-2E-30-30-33-38-39-31-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-33-3A-31-36-3A-34-31-2E-31-38-33-32-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 21:16:43,448 [21] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:10,ip:127.0.0.1:58127, Data: F3-02-07-00-01-08-73-01-1D-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-31-2E-38-37-39-30-37-34-31-2C-22-59-22-3A-35-2E-37-34-34-35-37-31-36-39-2C-22-5A-22-3A-31-32-34-2E-30-30-33-38-39-31-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-36-39-39-36-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-33-3A-31-36-3A-34-33-2E-34-31-34-33-38-39-34-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 21:16:57,905 [19] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:10,ip:127.0.0.1:58127, Data: F3-02-07-00-01-08-73-01-1E-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-38-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-31-2E-38-37-39-30-37-34-31-2C-22-59-22-3A-35-2E-37-34-34-35-37-31-36-39-2C-22-5A-22-3A-31-32-34-2E-30-30-33-38-39-31-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-33-3A-31-36-3A-35-37-2E-38-37-35-39-39-36-33-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 21:17:05,856 [21] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 23:28:50,535 [9] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 23:29:11,996 [19] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:11,ip:127.0.0.1:56071, Data: F3-02-07-00-01-08-73-01-1E-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-37-2E-35-35-33-38-37-31-32-2C-22-59-22-3A-35-2E-30-37-38-32-37-32-38-32-2C-22-5A-22-3A-31-32-30-2E-30-37-39-31-33-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-35-3A-32-39-3A-31-31-2E-38-34-33-33-37-30-35-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 23:29:25,433 [20] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:11,ip:127.0.0.1:56071, Data: F3-02-07-00-01-08-73-01-1F-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-31-2E-30-35-39-32-30-34-31-2C-22-59-22-3A-35-2E-32-37-39-39-33-31-30-37-2C-22-5A-22-3A-31-32-31-2E-38-38-33-35-39-31-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-35-3A-32-39-3A-32-35-2E-34-30-30-31-33-30-39-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 23:29:33,299 [9] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 23:31:52,394 [1] INFO  Photon.SocketServer.ApplicationBase - Application is stopping: AppId=SangoTest
2023-03-27 23:31:52,427 [14] ERROR Photon.SocketServer.ApplicationBase - System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at FantasyOfSango.Threads.SyncPlayerTransformThreads.Update() in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Threads\SyncPlayerTransformThreads.cs:line 27
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2023-03-27 23:31:52,557 [1] INFO  FantasyOfSango.SangoServer - Sango Server is Shut Down
2023-03-27 23:31:52,557 [1] INFO  Photon.SocketServer.ApplicationBase - Application stop: AppId=SangoTest
2023-03-27 23:57:01,174 [1] INFO  FantasyOfSango.SangoServer - Sango Server is Running
2023-03-27 23:57:01,190 [1] INFO  FantasyOfSango.SangoServer - Init all Component
2023-03-27 23:57:01,191 [1] INFO  Photon.SocketServer.ApplicationBase - Application start: AppId=SangoTest; AppPath=D:\FantasyOfSango\Server\TestServer\Photon_v4\FantasyOfSango_Photon\deploy\FantasyOfSango, Type=FantasyOfSango.SangoServer 
2023-03-27 23:57:14,801 [14] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-27 23:57:45,565 [14] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:0,ip:127.0.0.1:65437, Data: F3-02-07-00-01-08-73-01-1E-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-38-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-36-2E-38-35-38-36-32-37-33-2C-22-59-22-3A-35-2E-31-30-33-39-39-38-36-36-2C-22-5A-22-3A-31-31-39-2E-39-33-33-35-30-32-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-35-3A-35-37-3A-34-35-2E-35-32-32-36-37-30-39-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 23:57:48,410 [10] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:0,ip:127.0.0.1:65437, Data: F3-02-07-00-01-08-73-01-1C-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-37-2E-37-38-37-32-33-31-34-2C-22-59-22-3A-35-2E-33-37-39-30-38-38-34-2C-22-5A-22-3A-31-32-31-2E-32-33-36-34-36-35-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-36-39-39-36-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-35-3A-35-37-3A-34-38-2E-33-36-32-38-30-32-34-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 23:58:05,519 [14] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:0,ip:127.0.0.1:65437, Data: F3-02-07-00-01-08-73-01-1D-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-38-2E-35-32-39-35-38-36-38-2C-22-59-22-3A-35-2E-35-35-31-30-31-35-33-38-2C-22-5A-22-3A-31-32-32-2E-31-30-37-37-35-38-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-35-3A-35-38-3A-30-35-2E-34-39-34-34-39-36-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 23:58:10,267 [10] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:0,ip:127.0.0.1:65437, Data: F3-02-07-00-01-08-73-01-1E-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-38-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-38-2E-35-32-39-35-38-36-38-2C-22-59-22-3A-35-2E-35-35-31-30-31-35-33-38-2C-22-5A-22-3A-31-32-32-2E-31-30-37-37-35-38-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-34-39-2E-32-35-38-33-35-34-32-2C-22-59-22-3A-35-2E-37-39-35-37-30-30-30-37-2C-22-5A-22-3A-31-32-32-2E-39-30-35-34-34-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-37-54-31-35-3A-35-38-3A-31-30-2E-32-33-34-36-34-39-35-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-27 23:58:12,697 [15] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-27 23:58:37,006 [1] INFO  Photon.SocketServer.ApplicationBase - Application is stopping: AppId=SangoTest
2023-03-27 23:58:37,011 [16] ERROR Photon.SocketServer.ApplicationBase - System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at FantasyOfSango.Threads.SyncPlayerTransformThreads.Update() in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Threads\SyncPlayerTransformThreads.cs:line 27
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2023-03-27 23:58:37,028 [1] INFO  FantasyOfSango.SangoServer - Sango Server is Shut Down
2023-03-27 23:58:37,028 [1] INFO  Photon.SocketServer.ApplicationBase - Application stop: AppId=SangoTest
